# Generated by Django 5.0.7 on 2024-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
