# Generated by Django 5.0.7 on 2024-07-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_remove_car_company_car_location_car_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='review',
            field=models.TextField(default=None, max_length=10000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Car_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CarRental.car')),
            ],
        ),
    ]
