# Generated by Django 5.0.7 on 2024-07-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0003_car_is_active_car_review_car_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='Company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comapny', to='CarRental.company'),
            preserve_default=False,
        ),
    ]
