# Generated by Django 5.0.7 on 2024-07-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0004_company_remove_car_location_remove_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='CarRental.company'),
        ),
    ]
