# Generated by Django 5.0.7 on 2024-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0005_alter_car_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='car_images',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.IntegerField(default=1),
        ),
    ]
